// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiJAPemLIpmdI_rp_9czOA3EwDvB5s0M4',
    appId: '1:1017125920625:web:36029a5ebd52ee2998a0d0',
    messagingSenderId: '1017125920625',
    projectId: 'bill-reminder-3ecee',
    authDomain: 'bill-reminder-3ecee.firebaseapp.com',
    storageBucket: 'bill-reminder-3ecee.firebasestorage.app',
    measurementId: 'G-6DW5L11FTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBttd3iCSLmw90wfDfNve9aR7pwS-0ox2s',
    appId: '1:1017125920625:android:a23908e644ed239698a0d0',
    messagingSenderId: '1017125920625',
    projectId: 'bill-reminder-3ecee',
    storageBucket: 'bill-reminder-3ecee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXwK0rd_b7QlIDM-4Imk_sO-iJ3aC1uCc',
    appId: '1:1017125920625:ios:99a89e91dc01fa9b98a0d0',
    messagingSenderId: '1017125920625',
    projectId: 'bill-reminder-3ecee',
    storageBucket: 'bill-reminder-3ecee.firebasestorage.app',
    iosBundleId: 'com.example.billReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXwK0rd_b7QlIDM-4Imk_sO-iJ3aC1uCc',
    appId: '1:1017125920625:ios:99a89e91dc01fa9b98a0d0',
    messagingSenderId: '1017125920625',
    projectId: 'bill-reminder-3ecee',
    storageBucket: 'bill-reminder-3ecee.firebasestorage.app',
    iosBundleId: 'com.example.billReminder',
  );
}
